name: Build Images

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install qemu
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            Dockerfile
          image: myproj
          tags: latest ${{ github.sha }}
          archs: amd64, arm64
